### PR TITLE
Add show version sub_command.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
```
ruby -I ./lib -S exe/rukawa -v
rukawa 0.3.3
```
I implemented this command based on this 
[Reference](http://stackoverflow.com/questions/22809972/adding-a-version-option-to-a-ruby-thor-cli).

### CODE REVIEW

**Comment by joker1007** [comment]
I think, `version` is better than `--version`.
Because `--version` style is not necessary.

**Comment by hiroyuki-sato** [comment]
Thank you for reviewing.

I changed ``--version`` to ``version``

```
ruby -I lib -S exe/rukawa 
Commands:
  ...
  rukawa version(-v)
```

```
% ruby -I lib -S exe/rukawa -v
rukawa 0.3.3
```

```
% ruby -I lib -S exe/rukawa version
rukawa 0.3.3
```

**Comment by joker1007** [comment]
Thanks!

**Comment by hiroyuki-sato** [comment]
Thanks!

**Pull request merged**
